config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#show"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"

  get "/dashboard" => "dashboard#show"

  resources :games, only: [:new, :create]
  resources :leaderboards, only: [:show, :create]
  resources :activate_season, only: [:update]

  resources :seasons, only: [:index] do
    resources :leaderboards, only: [:index, :show]
    resources :games, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :season
  belongs_to :winner, class_name: :User, foreign_key: :winner_id, inverse_of: :winning_games
  belongs_to :loser, class_name: :User, foreign_key: :loser_id, inverse_of: :losing_games

  validates :season, presence: true
  validates :winner, presence: true
  validates :loser, presence: true
  validates :price_in_cents, presence: true

  enum status: { active: 0, nullified: 1 }

  scope :current_season, -> { where(season: Season.active_season) }

  def price_in_dollars
    (price_in_cents.to_f / 100).round(2)
  end
end

app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
  belongs_to :season
  has_many :records, dependent: :destroy

  validates :name, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :leaderboard
  belongs_to :user

  validates :win_count, presence: true
  validates :loss_count, presence: true
  validates :net_in_cents, presence: true

  MIN_GAME_COUNT = 25

  def self.eligible
    where("win_count + loss_count >= ?", MIN_GAME_COUNT)
  end

  def self.ineligible
    where("win_count + loss_count < ?", MIN_GAME_COUNT)
  end

  def self.create_for_user_and_leaderboard(user, leaderboard)
    season = leaderboard.season
    games_won = Game.active.where(season: season, winner: user)
    games_lost = Game.active.where(season: season, loser: user)
    net_in_cents = games_won.sum(:price_in_cents) - games_lost.sum(:price_in_cents)
    win_count = games_won.count
    loss_count = games_lost.count
    score = CalculateRecordScore.call(
      win_count: win_count,
      loss_count: loss_count,
      net_in_cents: net_in_cents,
    )

    create!(
      leaderboard: leaderboard,
      user: user,
      win_count: win_count,
      loss_count: loss_count,
      net_in_cents: net_in_cents,
      score: score,
    )
  end

  def self.by_score_and_win_average
    order(Arel.sql("score DESC, (records.win_count::float / ((case when records.win_count = 0 then 1 else records.win_count end) + records.loss_count)) desc"))
  end

  def win_average
    return 0 if games_played.zero?

    (win_count.to_f / games_played).round(3)
  end

  def net_in_dollars
    (net_in_cents.to_f / 100).round(2)
  end

  def games_played
    win_count + loss_count
  end
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :leaderboards, dependent: :destroy

  validate :one_active_season
  validates :name, presence: true
  validates :status, presence: true

  enum status: { active: 0, inactive: 1 }

  def self.active_season
    active.last
  end

  def activate!
    Season.transaction do
      Season.active_season.inactive!
      active!
    end
  end

  def game_count
    games.count
  end

  private

  def one_active_season
    return unless active? && Season.active.exists?

    errors.add(:status, "can only be active in one season")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :winning_games,
    class_name: :Game,
    foreign_key: :winner_id,
    dependent: :destroy,
    inverse_of: :winner
  has_many :losing_games,
    class_name: :Game,
    foreign_key: :loser_id,
    dependent: :destroy,
    inverse_of: :loser

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  enum status: { active: 0, inactive: 1 }

  def active_season_game_count
    Game
      .where(season: Season.active_season)
      .where("winner_id = :winner_id OR loser_id = :loser_id", winner_id: id, loser_id: id)
      .count
  end

  def game_count
    Game.current_season.where("winner_id = ? OR loser_id = ?", id, id).count
  end
end

app/controllers/activate_season_controller.rb
class ActivateSeasonController < ApplicationController
  def update
    if current_user.admin?
      season = Season.find(params[:id])

      season.activate!
    end

    redirect_to seasons_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "You must be logged in to access this page." if current_user.nil?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize

  def show
    @users = User.all
    @season = Season.active_season
    @recent_games = @season
      .games
      .includes(:winner, :loser)
      .order(created_at: :desc)
      .first(6)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authorize

  def new
    @game = Game.new
    @users = User.active
  end

  def create
    @game = Game.new(create_game_params)

    if @game.save
      redirect_to dashboard_path, notice: "Game recorded."
    else
      @users = User.active

      flash.now[:alert] = @game.errors.full_messages.join(", ")
      render :new
    end
  end

  def index
    @season = Season.find(params[:season_id])
    @games = @season
      .games
      .includes(:winner, :loser)
      .order(created_at: :desc)
  end

  private

  def create_game_params
    game_params
      .except(:price)
      .merge(
        price_in_cents: price_in_cents,
        season: Season.active_season,
      )
  end

  def game_params
    params.require(:game).permit(:winner_id, :loser_id, :price)
  end

  def price_in_cents
    price = game_params.fetch(:price)
    return if price.blank?

    (price.to_f * 100).to_i
  end
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :authorize

  def index
    @season = season
    @leaderboards = @season.leaderboards.order(created_at: :desc)
  end

  def show
    @leaderboard = Leaderboard.find(params[:id])
    @records = @leaderboard.records.by_score_and_win_average
  end

  def create
    if current_user.admin?
      LeaderboardService.run
    end

    redirect_to season_leaderboards_path(Season.active_season)
  end

  private

  def season
    if params[:season_id]
      Season.find(params[:season_id])
    else
      Season.active_season
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Season.all.order(:id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_authenticated, only: [:new]

  def new; end

  def create
    user = User.where("lower(email) = ?", lower_email).first

    if user&.authenticate(login_params.fetch(:password))
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def login_params
    params.require(:login).permit(:email, :password)
  end

  def lower_email
    login_params.fetch(:email).downcase
  end

  def redirect_if_authenticated
    redirect_to dashboard_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
  def formatted_win_average(win_average)
    win_average
      .round(3)
      .to_s
      .ljust(5, "0")
  end
end

app/views/dashboard/show.html.erb
<div class="row">
  <div class="col s12 section">
    <h4>Dashboard</h4>
  </div>
</div>

<div class="row">
  <%= link_to "View current season's leaderboards", season_leaderboards_path(@season) %>
</div>

<div class="row">
  <%= link_to "View seasons", seasons_path %>
</div>

<div class="row">
  <div class="col s12 section">
    <h5>Recent Games</h5>
  </div>
</div>

<div class="row recent-games-table">
  <%= render partial: "games/table", locals: { games: @recent_games } %>

  <% if @season.game_count > @recent_games.count %>
    <%= link_to "View all games", season_games_path(@season) %>
  <% end %>
</div>

<div class="row">
  <div class="col s12 section">
    <h5>Player Game Counts</h5>
  </div>
</div>

<div class="row">
  <table class="striped player-game-count-table">
    <thead>
      <tr>
        <th>Player</th>
        <th>Game count</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.game_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to new_game_path, class: "btn-floating btn-large waves-effect waves-light red dashboard__new-game-link" do %>
  <i class="material-icons">add</i>
<% end %>

app/views/games/_table.html.erb
<table class="striped s12">
  <thead>
    <tr>
      <th>Winner</th>
      <th>Loser</th>
      <th>Amount</th>
    </tr>
  </thead>

  <tbody>
    <% games.each do |game| %>
      <tr>
        <td><%= game.winner.name %></td>
        <td><%= game.loser.name %></td>
        <td><%= number_to_currency(game.price_in_dollars) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/index.html.erb
<div class="row">
  <div class="col s12 section">
    <h4><%= @season.name %> Season</h4>
  </div>
</div>

<div class="row active-season-games-table">
  <%= render partial: "table", locals: { games: @games } %>
</div>

app/views/games/new.html.erb
<div class="row">
  <div class="col s12 section">
    <h4>Record Game</h4>
  </div>
</div>

<%= form_for @game do |f| %>
  <div class="row">
    <div>
      <%= f.label :winner_id, "Winner" %>
      <%= f.collection_select :winner_id, @users, :id, :name, prompt: true %>
    </div>
  </div>

  <div class="row">
    <div>
      <%= f.label :loser_id, "Loser" %>
      <%= f.collection_select :loser_id, @users, :id, :name, prompt: true %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12 l6">
      <%= label_tag "game[price]", "Game price ($)" %>
      <%= number_field_tag "game[price]", nil, min: 0.5, step: 0.5 %>
    </div>
  </div>

  <div class="row">
    <div class="col s12 l6">
      <%= f.submit "Submit", class: "waves-effect waves-light btn indigo darken-4" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Theledger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path "logos/nba-ledger__stamp--72-72.jpg" %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path "logos/nba-ledger__stamp--114-114.jpg" %>">
    <link rel="apple-touch-icon" href="<%= asset_path "logos/nba-ledger__stamp--57-57.jpg" %>">
    <link rel="apple-touch-startup-image" href="<%= asset_path "logos/nba-ledger__full.jpg" %>">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper blue-grey darken-4">
        <%= link_to "The Ledger", root_path, class: "brand-logo center" %>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="flash-message indigo accent-2">
        <div class="container">
          <i class="material-icons left">check</i>

          <span class="flash--text"><%= flash[:notice] %></span>
        </div>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="flash-message red lighten-2">
        <div class="container">
          <i class="material-icons left">info</i>

          <span class="flash--text"><%= flash[:alert] %></span>
        </div>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/leaderboards/_table.html.erb
<table class="striped s12">
  <thead>
    <tr>
      <th>Name</th>
      <th>Wins</th>
      <th>Losses</th>
      <th>Average</th>
      <th>Net</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>
    <% records.each do |record| %>
      <tr>
        <td><%= record.user.name %></td>
        <td><%= record.win_count %></td>
        <td><%= record.loss_count %></td>
        <td><%= formatted_win_average(record.win_average) %></td>
        <td><%= number_to_currency(record.net_in_dollars) %></td>
        <td><%= record.score %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leaderboards/index.html.erb
<div class="row">
  <div class="col s12 section">
    <h4><%= @season.name %> Season Leaderboards</h4>
  </div>
</div>

<% if current_user.admin? && @season.active? %>
  <%= form_tag(leaderboards_path, method: :post) do %>
    <%= submit_tag "Create Leaderboard", class: "btn btn-primary" %>
  <% end %>
<% end %>

<div class="row">
  <ul class="collection leaderboards__list">
    <% @leaderboards.each do |leaderboard| %>
      <li class="collection-item"><%= link_to leaderboard.name, leaderboard_path(leaderboard) %></li>
    <% end %>
  </ul>
</div>

app/views/leaderboards/show.html.erb
<div class="row">
  <div class="col s12 section">
    <h4><%= @leaderboard.name %></h4>
  </div>
</div>

<div class="row leaderboard__table-wrapper--eligible">
  <h5>Eligible Players</h5>

  <%= render partial: "table", locals: { records: @records.eligible } %>
</div>

<div class="row leaderboard__table-wrapper--ineligible">
  <h5>Ineligible Players</h5>

  <%= render partial: "table", locals: { records: @records.ineligible } %>
</div>

app/views/seasons/index.html.erb
<div class="row">
  <div class="col s12 section">
    <h4>Seasons</h4>
  </div>
</div>

<div class="row">
  <ul class="collection">
    <% @seasons.each do |season| %>
      <li class="collection-item" id="season-<%= season.id %>">
        <div class="season__item-content">
          <%= link_to season.name, season_leaderboards_path(season) %>

          <% if season.active? %>
            <span class="new badge" data-badge-caption="active"></span>
          <% else %>
            <%= form_tag activate_season_path(season), method: :patch do %>
              <%= submit_tag "activate", class: "btn blue btn-small" %>
            <% end %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>